# Generated by Django 3.2.6 on 2021-12-29 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211229_2016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Product'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(choices=[('Sports Wear', 'Sports Wear'), ('Shoes', 'Shoes'), ('Trousers', 'Trousers'), ('Electronics', 'Electronics')], max_length=30),
        ),
    ]
